### ISSUE TITLE
Deno error while starting up server

### ISSUE THREAD

**Issue by basham** [earthstar-project/replica-server#4]
I'm trying to [start up a replica server on Glitch](https://glitch.com/edit/#!/oncheckin-server). Glitch is trying to start up with this command:

```
deno run --allow-net --allow-env https://deno.land/x/earthstar_replica_server@v1.1.0/server.ts
```

However, it throws an error partly through:

```
error: Expected {, got interface at https://deno.land/x/earthstar_streaming_rpc@3.2.3/src/types.ts:69:7
```

I'm guessing its because [this line](https://deno.land/x/earthstar_streaming_rpc@3.2.3/src/types.ts#L69) is this:

```ts
export interface IConnection<
    MethodsType extends FnsBag,
> {
```

And perhaps it should be this?

```ts
export interface IConnection<MethodsType extends FnsBag> {
```

**Comment by basham** [comment]
After some more investigation, it seems like it was some incompatibility with this version of deno that was installed on Glitch (I had remixed it from another project):

```
deno 1.4.6
v8 8.7.220.3
typescript 4.0.3
```

Replica Server works on macOS, with the latest version of deno (1.19.1). However, this version is not compatible with Glitch. The issue is mostly elaborated here:

https://github.com/denoland/deno/issues/13516

It suggests that v1.18.0 may be the latest version of deno that would support the current Glitch Linux environment. So, I installed it in Glitch terminal:

```
curl -fsSL https://deno.land/x/install/install.sh | sh -s v1.18.0
```

Deno runs now, and it has gotten past the original problem posted in this issue. I'm still working through other problems with it, after that point.

**Comment by sgwilym** [comment]
Ooh, thanks for looking into how this can work with Glitch. If you're looking to easily deploy your own replica server, it's also worth looking at this Dockerised version of replica-server: https://github.com/sandreae/earthstar-docker

Thank you for experimenting! replica-server right now is not really user-friendly, and meant as a stopgap solution — but part of our funded work is doing the user-friendly part, and soon. :)

**Comment by basham** [comment]
Here are some more specific instructions for how I set up Glitch for replica server, using its Terminal.

Install deno. (Again, v1.18.0 may be the most recent and compatible version.)

```
curl -fsSL https://deno.land/x/install/install.sh | sh -s v1.18.0
```

Move the deno binary from its installed directory to a local bin, so that you can call it directly (without adding it to some PATH configuration). Maybe a symbolic link would be better?

```
mkdir .local
mkdir .local/bin
mv .deno/bin/deno .local/bin/deno
```

Make the data directory for the replica server, since it doesn't do it itself.

```
mkdir data
```

I'm still working out how to properly set up other parts of it. I really like the `Makefile` solution I've been seeing in some of the Earthstar repos, as a sort of deno script runner, that doesn't require another install, like [Velociraptor](https://velociraptor.run/).

**Comment by sgwilym** [comment]
By the way, one more thing to consider: the node subpath of earthstar-streaming-rpc exports a `TransportHtmlServerExpress` which you can use to build an Express server which could more easily run on Glitch.

You'd have to build the features from replica-server like backwards compatibility and allow list on top, but you'd have complete control at least :)

**Comment by sgwilym** [comment]
There is now a variant of the Replica server specifically made for Glitch, based on a Node-friendly variant!
