### ISSUE TITLE
Add config for data directory

### ISSUE THREAD

**Issue by basham** [earthstar-project/replica-server#6]
In v1.1.0, all replicas are stored in a `data` folder. Allow this location to be configured.

This is important for environments like Glitch, in which a top-level `data` folder will be copied when remixed. For Glitch, you would want to configure it to use the [private `.data` folder](https://help.glitch.com/kb/article/23-remix/).

**Comment by sgwilym** [comment]
Thank you, this seems like a good feature to add and not too difficult to do either.

**Comment by sgwilym** [comment]
This is now configurable via the `ExtensionKnownShares` extension!
